Configure pre-commit tool
kpi-web-guild/django-girls-blog-mikescor pull request #10
Opened 2017-03-07 21:44 UTC by mikescor

close #6

2017-03-07 21:48 UTC, Miseracle approved these changes

2017-03-07 21:55 UTC, klochenok approved these changes

2017-03-08 07:02 UTC, DrEdi reviewed
Do not close issue before anyone approved it. You can do this in latest commit while merge

2017-03-08 07:03 UTC, DrEdi approved these changes

2017-03-09 09:05 UTC, webknjaz requested changes

2017-03-09 09:05 UTC, webknjaz commented on .pre-commit-config.yaml
> +    sha: master
Please run `pre-commit autoupdate` to have sha hash of the latest commit here

2017-03-09 11:21 UTC, webknjaz approved these changes
LGTM

2017-03-09 11:28 UTC, merged