TravisCI integration
kpi-web-guild/django-girls-blog-mikescor pull request #11
Opened 2017-03-10 20:07 UTC by mikescor

2017-03-10 20:35 UTC, Miseracle approved these changes

2017-03-10 20:46 UTC, webknjaz requested changes
I assume you forgot to set up pre-commit in your local repo

2017-03-10 21:32 UTC, DrEdi approved these changes

2017-03-11 15:43 UTC, webknjaz requested changes
please rebase this branch on top of master

2017-03-17 10:43 UTC, webknjaz approved these changes

2017-03-17 10:45 UTC, merged