Feature/initial django files
kpi-web-guild/django-girls-blog-mikescor pull request #12
Opened 2017-04-12 12:48 UTC by mikescor

2017-04-12 18:09 UTC, Miseracle commented
Please, fill the description and PR title with valid info about PR.

2017-04-13 15:36 UTC, webknjaz requested changes

2017-04-13 15:36 UTC, webknjaz commented on blog/__init__.py
> +"""Don't write here."""
It's a stupid docstring. Why would you even need this module?

2017-04-13 15:36 UTC, webknjaz commented on blog/apps.py
> +"""Configure app here."""
The docstring must describe the module and not be some call to action.

2017-04-13 15:36 UTC, webknjaz commented on blog/apps.py
> +    """Configuration."""
Be more specific.

2017-04-13 15:36 UTC, webknjaz commented on blog/forms.py
> +"""This module keeps the collection of form declarations representing HTML forms."""
This is too verbose.

2017-04-13 15:36 UTC, webknjaz commented on blog/forms.py
> +    """Form for Post model."""
No. It's a form for Post entity. Don't write obvious things I can see two lines below.

2017-04-13 15:36 UTC, webknjaz commented on blog/migrations/0001_initial.py
> +"""Migrations."""
Normally, autogenerated things aren't being checked by linter.

2017-04-13 15:36 UTC, webknjaz commented on blog/migrations/0001_initial.py
> +"""Migrations."""
And it's a single migration, not multiple.

2017-04-13 15:36 UTC, webknjaz commented on blog/migrations/__init__.py
> +"""Migrations."""
O'rly?

2017-04-13 15:36 UTC, webknjaz commented on blog/models.py
> +    """Model for post in blog."""
It's obvious that it's a model. I can see it a line above.

2017-04-13 15:36 UTC, webknjaz commented on blog/models.py
> +        """Return title of the post."""
Really? Isn't it what is stated in the next line?

2017-04-13 15:36 UTC, webknjaz commented on blog/views.py
> +"""All views of project."""
I think this description is meaningless.

2017-04-13 15:36 UTC, webknjaz commented on blog/views.py
> +from django.utils import timezone
It's nice to separate import sections with an empty line here.

2017-04-13 15:36 UTC, webknjaz commented on blog/views.py
> +    """Return page with form for adding new post."""
I think it's "render". Well, maybe "show".

2017-04-13 15:36 UTC, webknjaz commented on blog/views.py
> +    """Return page for editing post."""
"return" looks ugly here as well.

2017-04-13 15:36 UTC, webknjaz commented on manage.py
> +"""Manage settings of project."""
Oh no, it manages the app, not its settings.

2017-04-13 15:36 UTC, webknjaz commented on mysite/__init__.py
> +"""Don't write here."""
Really? :hankey: :hankey: :hankey:

2017-04-13 15:36 UTC, webknjaz commented on mysite/urls.py
> +urlpatterns = [
You must import urls from blog rather than duplicating them.

2017-05-02 15:49 UTC, webknjaz requested changes
* Rethink the purpose of docstrings, read PEP 257;
* Fix current comments;
* Fix previous comments as well;
* Write sane commit messages and docstrings.

2017-05-02 15:49 UTC, webknjaz commented on blog/apps.py
> +"""Configuring application."""
It it a process or a module?

2017-05-02 15:49 UTC, webknjaz commented on blog/apps.py
> +"""Configuring application."""
It it a process or a module?

2017-05-02 15:49 UTC, webknjaz commented on blog/migrations/0001_initial.py
> +"""Migration settings."""
no.

2017-05-02 15:49 UTC, webknjaz commented on blog/models.py
> +        """Get title of the post."""
No.

2017-05-02 15:49 UTC, webknjaz commented on blog/views.py
> +"""Configuration for views."""
no.

2017-05-02 15:49 UTC, webknjaz commented on blog/views.py
> +    """Get page with form for adding new post."""
no

2017-05-02 15:49 UTC, webknjaz commented on blog/views.py
> +    """Get page for editing post."""
no.

2017-05-02 15:49 UTC, webknjaz commented on manage.py
> +"""App management."""
it's not a process. see pep257

2017-05-02 15:49 UTC, webknjaz commented on manage.py
> +"""App management."""
it's not a process. see pep257

2017-05-04 10:20 UTC, DrEdi commented on blog/migrations/0001_initial.py
> +"""Initial migration. Autocreated.
you have not to write this for autocreated files

2017-05-04 10:24 UTC, webknjaz requested changes

2017-05-04 10:24 UTC, webknjaz commented on blog/models.py
> +        """Convert an object to a string."""
"Render Post as its title."

2017-05-04 12:09 UTC, webknjaz requested changes

2017-05-04 12:09 UTC, webknjaz commented on .pre-commit-config.yaml
> +        exclude: migrations
you'd better use full relative path `blog/migrations` to prevent accidentally ignoring smth important.

2017-05-04 12:29 UTC, webknjaz approved these changes
LGTM

2017-05-04 12:43 UTC, merged