Django first project
kpi-web-guild/django-girls-blog-mikescor pull request #3
Opened 2017-02-04 11:02 UTC by mikescor

2017-02-04 13:00 UTC, DrEdi requested changes
Please, add views and urls. This is not complete even for first push.

upd: 
everything you did here has no any relation to branch name. You create Django project, but in branch you say that you want to INTEGRATE IT WITH TRAVIS. 

upd2:
also i didn't see in issues that you had to do this. 
Leave this for later and now start to do what you have in issues.
https://github.com/kpi-web-guild/django-girls-blog-mikescor/issues/1
this is your first exercise

2017-02-04 13:00 UTC, DrEdi commented on blog/models.py
> +class Post(models.Model):
Where is docstrings?
Did you user pre-commit for checking pep257?

2017-02-04 13:00 UTC, DrEdi commented on blog/models.py
> +    def publish(self):
methods also should have docstings

2017-02-04 13:00 UTC, DrEdi commented on mysite/settings.py
> +"""
you don't really need this now. Leave only first string `Django settings for mysite project.`

2017-02-04 18:27 UTC, mikescor commented
thanks for tips.

2017-02-04 21:34 UTC, webknjaz commented on blog/.directory
> +[Dolphin]
It's a bullshit. **Don't ever commit useless files into the repo**

2017-02-04 21:35 UTC, webknjaz commented on .gitignore
> +myvenv/
Okay, now configure `pyenv` w/ `pyenv-virtualenv` and use it instead

2017-02-04 21:35 UTC, webknjaz commented on .gitignore
> +
Why did you add so many new lines?

2017-02-04 21:36 UTC, webknjaz commented on blog/migrations/.directory
> +[Dolphin]
:hankey:

2017-02-04 21:36 UTC, webknjaz commented on mysite/.directory
> +[Dolphin]
:hankey:

2017-02-04 21:38 UTC, webknjaz requested changes
Let's postpone this PR until automatic linters checking configured.

2017-02-05 12:58 UTC, MaxymVlasov commented on blog/admin.py
> +from .models import Post
What your `<app>` name in template `from <app>.models import <ModelName>`?

2017-02-09 07:30 UTC, webknjaz commented on blog/admin.py
> +from .models import Post
@MaxymVlasov Does it matter?

2017-05-04 12:43 UTC, closed without merging